package net.protobufs;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: steammessages_physicalgoods.steamclient.proto

public final class SteammessagesPhysicalgoodsSteamclient {
  private SteammessagesPhysicalgoodsSteamclient() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CPhysicalGoods_RegisterSteamController_RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CPhysicalGoods_RegisterSteamController_Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string serial_number = 1;</code>
     */
    boolean hasSerialNumber();
    /**
     * <code>optional string serial_number = 1;</code>
     */
    java.lang.String getSerialNumber();
    /**
     * <code>optional string serial_number = 1;</code>
     */
    com.google.protobuf.ByteString
        getSerialNumberBytes();
  }
  /**
   * Protobuf type {@code CPhysicalGoods_RegisterSteamController_Request}
   */
  public static final class CPhysicalGoods_RegisterSteamController_Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CPhysicalGoods_RegisterSteamController_Request)
      CPhysicalGoods_RegisterSteamController_RequestOrBuilder {
    // Use CPhysicalGoods_RegisterSteamController_Request.newBuilder() to construct.
    private CPhysicalGoods_RegisterSteamController_Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CPhysicalGoods_RegisterSteamController_Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CPhysicalGoods_RegisterSteamController_Request defaultInstance;
    public static CPhysicalGoods_RegisterSteamController_Request getDefaultInstance() {
      return defaultInstance;
    }

    public CPhysicalGoods_RegisterSteamController_Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CPhysicalGoods_RegisterSteamController_Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              serialNumber_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SteammessagesPhysicalgoodsSteamclient.internal_static_CPhysicalGoods_RegisterSteamController_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SteammessagesPhysicalgoodsSteamclient.internal_static_CPhysicalGoods_RegisterSteamController_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request.class, SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request.Builder.class);
    }

    public static com.google.protobuf.Parser<CPhysicalGoods_RegisterSteamController_Request> PARSER =
        new com.google.protobuf.AbstractParser<CPhysicalGoods_RegisterSteamController_Request>() {
      public CPhysicalGoods_RegisterSteamController_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CPhysicalGoods_RegisterSteamController_Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CPhysicalGoods_RegisterSteamController_Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERIAL_NUMBER_FIELD_NUMBER = 1;
    private java.lang.Object serialNumber_;
    /**
     * <code>optional string serial_number = 1;</code>
     */
    public boolean hasSerialNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string serial_number = 1;</code>
     */
    public java.lang.String getSerialNumber() {
      java.lang.Object ref = serialNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serialNumber_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string serial_number = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSerialNumberBytes() {
      java.lang.Object ref = serialNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serialNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      serialNumber_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSerialNumberBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSerialNumberBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CPhysicalGoods_RegisterSteamController_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CPhysicalGoods_RegisterSteamController_Request)
        SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesPhysicalgoodsSteamclient.internal_static_CPhysicalGoods_RegisterSteamController_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesPhysicalgoodsSteamclient.internal_static_CPhysicalGoods_RegisterSteamController_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request.class, SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request.Builder.class);
      }

      // Construct using SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serialNumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SteammessagesPhysicalgoodsSteamclient.internal_static_CPhysicalGoods_RegisterSteamController_Request_descriptor;
      }

      public SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request getDefaultInstanceForType() {
        return SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request.getDefaultInstance();
      }

      public SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request build() {
        SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request buildPartial() {
        SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request result = new SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serialNumber_ = serialNumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request) {
          return mergeFrom((SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request other) {
        if (other == SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request.getDefaultInstance()) return this;
        if (other.hasSerialNumber()) {
          bitField0_ |= 0x00000001;
          serialNumber_ = other.serialNumber_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object serialNumber_ = "";
      /**
       * <code>optional string serial_number = 1;</code>
       */
      public boolean hasSerialNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string serial_number = 1;</code>
       */
      public java.lang.String getSerialNumber() {
        java.lang.Object ref = serialNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serialNumber_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string serial_number = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSerialNumberBytes() {
        java.lang.Object ref = serialNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serialNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serial_number = 1;</code>
       */
      public Builder setSerialNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serialNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serial_number = 1;</code>
       */
      public Builder clearSerialNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serialNumber_ = getDefaultInstance().getSerialNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serial_number = 1;</code>
       */
      public Builder setSerialNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serialNumber_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CPhysicalGoods_RegisterSteamController_Request)
    }

    static {
      defaultInstance = new CPhysicalGoods_RegisterSteamController_Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CPhysicalGoods_RegisterSteamController_Request)
  }

  public interface CPhysicalGoods_RegisterSteamController_ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CPhysicalGoods_RegisterSteamController_Response)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code CPhysicalGoods_RegisterSteamController_Response}
   */
  public static final class CPhysicalGoods_RegisterSteamController_Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CPhysicalGoods_RegisterSteamController_Response)
      CPhysicalGoods_RegisterSteamController_ResponseOrBuilder {
    // Use CPhysicalGoods_RegisterSteamController_Response.newBuilder() to construct.
    private CPhysicalGoods_RegisterSteamController_Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CPhysicalGoods_RegisterSteamController_Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CPhysicalGoods_RegisterSteamController_Response defaultInstance;
    public static CPhysicalGoods_RegisterSteamController_Response getDefaultInstance() {
      return defaultInstance;
    }

    public CPhysicalGoods_RegisterSteamController_Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CPhysicalGoods_RegisterSteamController_Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SteammessagesPhysicalgoodsSteamclient.internal_static_CPhysicalGoods_RegisterSteamController_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SteammessagesPhysicalgoodsSteamclient.internal_static_CPhysicalGoods_RegisterSteamController_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response.class, SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response.Builder.class);
    }

    public static com.google.protobuf.Parser<CPhysicalGoods_RegisterSteamController_Response> PARSER =
        new com.google.protobuf.AbstractParser<CPhysicalGoods_RegisterSteamController_Response>() {
      public CPhysicalGoods_RegisterSteamController_Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CPhysicalGoods_RegisterSteamController_Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CPhysicalGoods_RegisterSteamController_Response> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CPhysicalGoods_RegisterSteamController_Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CPhysicalGoods_RegisterSteamController_Response)
        SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesPhysicalgoodsSteamclient.internal_static_CPhysicalGoods_RegisterSteamController_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesPhysicalgoodsSteamclient.internal_static_CPhysicalGoods_RegisterSteamController_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response.class, SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response.Builder.class);
      }

      // Construct using SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SteammessagesPhysicalgoodsSteamclient.internal_static_CPhysicalGoods_RegisterSteamController_Response_descriptor;
      }

      public SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response getDefaultInstanceForType() {
        return SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response.getDefaultInstance();
      }

      public SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response build() {
        SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response buildPartial() {
        SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response result = new SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response) {
          return mergeFrom((SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response other) {
        if (other == SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SteammessagesPhysicalgoodsSteamclient.CPhysicalGoods_RegisterSteamController_Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CPhysicalGoods_RegisterSteamController_Response)
    }

    static {
      defaultInstance = new CPhysicalGoods_RegisterSteamController_Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CPhysicalGoods_RegisterSteamController_Response)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CPhysicalGoods_RegisterSteamController_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CPhysicalGoods_RegisterSteamController_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CPhysicalGoods_RegisterSteamController_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CPhysicalGoods_RegisterSteamController_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-steammessages_physicalgoods.steamclien" +
      "t.proto\032,steammessages_unified_base.stea" +
      "mclient.proto\"G\n.CPhysicalGoods_Register" +
      "SteamController_Request\022\025\n\rserial_number" +
      "\030\001 \001(\t\"1\n/CPhysicalGoods_RegisterSteamCo" +
      "ntroller_Response2\233\002\n\rPhysicalGoods\022\324\001\n\027" +
      "RegisterSteamController\022/.CPhysicalGoods" +
      "_RegisterSteamController_Request\0320.CPhys" +
      "icalGoods_RegisterSteamController_Respon" +
      "se\"V\202\265\030RRecords a serial number and the ",
      "calling user\'s account info for warranty" +
      " purposes.\0323\202\265\030/A service to use physica" +
      "l goods related methodsB\003\200\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          SteammessagesUnifiedBaseSteamclient.getDescriptor(),
        }, assigner);
    internal_static_CPhysicalGoods_RegisterSteamController_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CPhysicalGoods_RegisterSteamController_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CPhysicalGoods_RegisterSteamController_Request_descriptor,
        new java.lang.String[] { "SerialNumber", });
    internal_static_CPhysicalGoods_RegisterSteamController_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CPhysicalGoods_RegisterSteamController_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CPhysicalGoods_RegisterSteamController_Response_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(SteammessagesUnifiedBaseSteamclient.methodDescription);
    registry.add(SteammessagesUnifiedBaseSteamclient.serviceDescription);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    SteammessagesUnifiedBaseSteamclient.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
